name: base
channels:
 - conda-forge
dependencies:
 - holoviews
 - hvplot
 - colorcet
 - numpy
 - pandas
 - astropy >= 5.3
 - bokeh >= 3.1.1
 - panel >= 1.1.0
 - uranography >= 1.4.1
 - param
 - git
 - botocore
 - boto3
 - wget
 - lsst-efd-client
 - rubin-scheduler >= 3.10.0
 - rubin-sim >= 2.2.4
 - scikit-learn
 - pip
 - pip:
   - lsst.resources
