name: base
channels:
 - conda-forge
dependencies:
 - holoviews
 - hvplot
 - colorcet
 - numpy
 - pandas
 - astropy >= 5.3
 - uranography >= 1.1.0
 - bokeh >= 3.1.1
 - panel >= 1.1.0
 - uranography
 - param
 - git
 - botocore
 - boto3
 - wget
 - lsst-efd-client
 - rubin-scheduler = 3.6.0
 - rubin-sim
 - pip
 - pip:
   - lsst.resources
