name: base
channels:
 - conda-forge
dependencies:
 - holoviews
 - hvplot
 - colorcet
 - numpy
 - pandas
 - astropy >= 5.3
 - rubin-sim >= 1.3.0
 - uranography >= 1.1.0
 - bokeh >= 3.1.1
 - panel >= 1.1.0
 - uranography
 - param
 - git
 - pip
